name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_9X4RLDe9omW6peHnfkZqHBB4
          vercel-project-id: prj_ctRIJSv8Pg9ZbEsTeJnwKks5h3te
          vercel-args: '--prod'
